
pcm.snapcast_format {
    type plug
    slave {
        pcm "snapcast_raw"
        format "S16_LE"
        rate 48000
        channels 2
    }
}

pcm.snapcast_raw {
    type file
    slave.pcm "null"
    file "/tmp/snapfifo"
    format "raw"
}

pcm.plexamp_output {
    type plug
    slave.pcm "snapcast_format"
    hint {
        show on
        description "Snapcast"
    }
}
